### ISSUE TITLE
Update method matching on argument names and quantity

### ISSUE THREAD

**Issue by philipweiser** [JonPSmith/EfCore.GenericServices#12]
Case:
DDDEntity
{
string Prop1{get; private set}
string Prop2{get; private set}

public void SetProp1(string prop1){Prop1 = prop1;} 
public void SetProp2(string prop2){Prop2 = prop2;} 
public void SetProp1And2(string prop1, string prop2) {Prop1 = prop1; Prop2 = prop2;} 
}

using CRUDService, call UpdateAndSave on a DTO that has both properties Prop1 and Prop2.  It can't decide which method to use, as it sees all three as valid setters, even though only one of the methods can take both parameters.

Is it possible to force it to use the two-parameter method automatically (without having to specify "SetProp1And2" as a second argument?  And would it be a reasonable thing to do?

The explicit error message I'm getting:
System.InvalidOperationException : There are multiple method, so you need to define which one you want used via the method parameter. The possible options are:
SetProp1And2(2 params)
SetProp2(1 params)
SetProp1(1 params)

I was hoping that it would automatically map to the SetProp1And2 method since it has both, without having to explicitly pass the name of the method.

**Comment by JonPSmith** [comment]
Hi @philipweiser,

I looked into your case and I can see that a a DTO with the two properties  `SetProp1And2` would fit to all three options. That isn't what I wanted, and sometime I will improve the code to group by number of parameters and take the one with the highest number of parameters. I will leave this issue open so that I remember to fix this

In the meantime you can use the name of the DTO to cause a match. I have added a new section to the GenericServices docs which [describes the matching process](https://github.com/JonPSmith/EfCore.GenericServices/wiki/DDD-entity-patterns#how-genericservices-matches-a-dto-to-a-ddd-method). Step 3 might be useful to you, but it depends on whether you use the same DTO/VM on both calls to your single item methods. Certainly the DTO name approach 

Thanks for adding this issue.
