### ISSUE TITLE
How to use https://fluentvalidation.net for Models and Dtos

### ISSUE THREAD

**Issue by djoyrocks** [JonPSmith/EfCore.GenericServices#14]
Hi 

How to use https://fluentvalidation.net for Models and Dtos with GenericServices

**Comment by JonPSmith** [comment]
Hi @djoyrocks,

There isn't anything in GenericServices at the moment that could handle that. I will think about it (maybe something that runs before the call to SaveChanges), but I am very busy at the moment so its not going to get done quickly.

If you need a solution quickly I can think of a way to do this, but its not that nice. You could override the SaveChanges/SaveChangesAsync in your DbContext and run your fluentvalidation tests in there. If there is a validation failure you then throw an exception with the validation errors in that exception. Then you provide a [SQL error handler](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Configuration-options#genericservicesconfigsavechangesexceptionhandler) via the configuration in which you look for  your validation exception and turn the errors in that exception into a `IStatusGeneric` state to fit in with GenircServices. Bit of a kludge, but it would work.

*Note: You need to turn on the normal validation, otherwise the SQL error handler isn't used. This means the standard validation is run before your fluentvalidation is run.*

I'll keep this open for when I get time to look at this.
