### ISSUE TITLE
SortPageFilterPageOption does not work as intended

### ISSUE THREAD

**Issue by tesnep** [JonPSmith/EfCore.GenericServices#20]
I don't understand how PrevCheckState and NewCheckState is supposed to work when this class is instantiated for every request. 
   ```
 public async Task SetupRestOfDto<T>(IQueryable<T> query)
        {
            NumPages = (int) Math.Ceiling(
                (double) (await query.CountAsync())/PageSize);
            PageNum = Math.Min(
                Math.Max(1, PageNum), NumPages);                                                            

            var newCheckState = GenerateCheckState();
            if (PrevCheckState != newCheckState)
                PageNum = 1;

            PrevCheckState = newCheckState;
        }

        private string GenerateCheckState()
        {
            return $"{(int) FilterBy},{FilterValue},{PageSize},{NumPages}";
        }
```

PageNum is then always set to 1.

**Comment by JonPSmith** [comment]
Firstly, this is nothing to do with GenericServices - what you are seeing is my example application that demonstrates how to use GenericServices in an ASP.NET Core application.

The  `if (PrevCheckState != newCheckState)` test is used to reset the page number if anything other than the page number is changed. You need this because if you did a filter, sort etc, then you need the page number to return to 1. The PrevCheckState is saved in the razor page so that you test the new state against the previous state.
