### ISSUE TITLE
ICrudServices for updating soft delete property using query filters

### ISSUE THREAD

**Issue by Lerseb** [JonPSmith/EfCore.GenericServices#54]
Hi Jon,
Thanks for making this library available, it is awesome.

I am trying to change the flag "SoftDelete" to false (This entity has already been soft deleted).
I am able to "get" the Dto using a ProjectFromEntityToDto method with .IgnoreQueryFilters.
I change the value of the SoftDeleted property of this Dto (to false) and my Dto is correct.
When I use service.UpdateAndSave method on this Dto, the SoftDeleted property doesn't get updated to false.
Is there a way to IgnoreQueryFilters when using GenericServices UpdateAndSave?
Thanks

**Comment by JonPSmith** [comment]
Hi @Lerseb,

No, sorry. The service.UpdateAndSave has to load the entity, and because the SoftDeleted flag is true it won't load it. You are going to write direct LINQ to handle that. Remember, if you have an instance of the `ICrudServices`/`ICrudServicesAsync` service it has a property called `Context` that contains the EF Core context.

PS. I am working on a library called  [EfCore.SoftDeleteServices](https://github.com/JonPSmith/EfCore.SoftDeleteServices) that will handle SoftDelete, but its not ready yet. That library is some months away from being released as I still have some work to do on my book and updating all my libraries to EF Core 5 first.

**Comment by Lerseb** [comment]
Thanks Jon,
I hesitated to raise it as an issue but thanks to your answer I won't be looking for something that doesn't exist.
I will do it the old way.
I will follow your lead to move on to .net 5.0 and Ef Core 5.0 when it will be mature and the libraries will support it.
Thanks again for the great book, libraries and quick answers.
