### ISSUE TITLE
Issues using with Blazor Server

### ISSUE THREAD

**Issue by cornonthecobb** [JonPSmith/EfCore.GenericServices#57]
Im curious if you have tested this library with Blazor server side. I run into issues using crud services in components where a crud service will return an error that gets handled correctly and added to the IStatusGeneric collection. I correct the error and resubmit but the same error is still present. I suspect this is likely due to how the dbcontext/crudservice is scoped to the lifetime of the component. I was curious if you have a way or were looking into using IDbContextFactory as a possible enhancement or addition to the code base.

**Comment by JonPSmith** [comment]
Blazor server side has some limitations because of concurrent application's DbContext, and as you say you need to use `IDbContextFactory`. That rules out the usage of DI to provide the application's DbContext.

I would suggest you use [the code I use when writing unit tests](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Unit-testing-your-code), e.g.

```c#
        var utData = context.SetupSingleDtoAndEntities<BookTitle>();
        var service = new CrudServices(context, utData.ConfigAndMapper);
```

You can then use the `service` instance to use, but of course you still need to deal with concurrent calls to the service/context.

PS. This example just registers the  `BookTitle` DTO, but if you look at the unit test code it can register more than one class/DTO.

**Comment by cornonthecobb** [comment]
Thanks, I will take a look.

 I did some more investigating and found out that blazor server does not have a scope that works per request as things are tied to the component. 

Microsoft offers a way to add scoped services to a component using @inherits OwningComponentBase which allows access to the DI container. I would basically have to create a new scope for each request I wanted to do to make it behave the old way.

Currently a rough example.

`@code {
    [Parameter]
    public string Title { get; set; }
    [Parameter]
    public EventCallback<AddLocationDto> OnLocationAddedCallback { get; set; }

    public AddLocationDto AddLocationDto { get; set; } = new AddLocationDto();
    private CustomValidator customValidator;
    private EditContext _editContext;
    private bool IsCrudServicesLoading;

    private ICrudServicesAsync<HaiDbContext> CrudServicesAsync;
    protected override void OnInitialized()
    {

        _editContext = new EditContext(AddLocationDto);
    }

    public async Task OnSubmit(AddLocationDto args)
    {
        CrudServicesAsync = ScopedServices.CreateScope().ServiceProvider.GetService<ICrudServicesAsync<HaiDbContext>>();

        customValidator.ClearErrors();

        IsCrudServicesLoading = true;

        var location = await CrudServicesAsync.CreateAndSaveAsync(args);
        IsCrudServicesLoading = false;

        if (CrudServicesAsync.HasErrors)
        {
            var errors = new Dictionary<string, List<string>>();

            foreach (var error in CrudServicesAsync.Errors)
            {
                errors.Add("",new List<string>(){error.ErrorResult.ErrorMessage});
            }

            if (errors.Count() > 0)
            {
                customValidator.DisplayErrors(errors);
            }
        }
        else
        {
            NotificationService.Notify(NotificationSeverity.Info, $"New location: {args.Name} has been added.", duration: 4000d);
            await OnLocationAddedCallback.InvokeAsync(location);
            DialogService.Close();
        }

    }
}`

**Comment by JonPSmith** [comment]
The recommend way is to use `IDbContextFactory`, so I would use that. I assume you have looked at the docs on [EF Core and Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-5.0), which I found very useful.

**Comment by cornonthecobb** [comment]
Thanks, I am using the DbContext factory in the start up configure services.

**Comment by rcdailey** [comment]
My hesitation (and dislike) in using `IDbContextFactory` is the manual disposal of the context. Basically:

- Do I create one context per CRUD operation, save, and dispose?
- Do I move the context scope "up" a level to "batch" various actions together, save, and then dispose?

Maybe there are more options. But both of these have downsides. The second one has performance benefits but the downside is now you have disposal semantics leak out and it limits the kind of DI container injections you can do (e.g. you have to be careful about injecting services directly versus factories for those services. If you do the former, you lock your context to the lifecycle of the owning object, defeating the purpose).

I just all-around don't like it. I almost feel like a more appropriate solution is to just use ASP.NET Hosted WASM instead of Blazor Server. Then you can use DI-injected contexts just fine.

**Comment by JonPSmith** [comment]
Hi @rcdailey,

I think your comments are about Blazor and EF Core rather than on EfCore.GerericServices because you can't "batch" calls to EfCore.GerericServices. Using EF Core in Blazor front-end code has to be written quite carefully because EF Core's `DbContext` is not thread-safe. 

I haven't used Blazor (I'm mainly a back-end developer), but if I did I would create a back-end API as you describe in you last paragraph.

**Comment by cornonthecobb** [comment]
I agree that using WASM would be the best solution. For times sake, I ended up using Blazor's [OwningCoponentBase ](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-5.0&pivots=webassembly#utility-base-component-classes-to-manage-a-di-scope )class to basically implement a service locator pattern to get by for now.

The usage of what Im doing is the equivalent of creating one context per crud request.

``
   async Task Submit(AddLocationFormDto arg)
   {
       var crudServicesAsyncScoped = ScopedServices.CreateScope().ServiceProvider.GetRequiredService<ICrudServicesAsync<HaiDbContext>>();

//rest of submit handling code

   }``

**Comment by whit4576** [comment]
Hi Jon - Thanks for your reply. Here are a couple of follow-up questions  Have reviewed issue 57 and have a couple follow-up questions:

1. Which interfaces and services are recommended to be registered for bunit tests? Have tried using ICrudServicesAsync and CrudServicesAsync for the interface and service - and There were no assembles to scan! (Parameter 'assembliesToScan') in spite of specifying DTO.

Program
builder.Services.GenericServicesSimpleSetup<AppNameContext>(
  Assembly.GetAssembly(typeof(NameDto)));

Bunit Unit Test
Below is the code for registering with the Unit Test
   Services.GenericServicesSimpleSetup<AppNameContext>();
            Assembly.GetAssembly(typeof(AppNameDto));

**Comment by JonPSmith** [comment]
Read the documentation, which has a [Unit testing your code](https://github.com/JonPSmith/EfCore.GenericServices/wiki/Unit-testing-your-code) page.
