### ISSUE TITLE
Not sure if issue or working as intended

### ISSUE THREAD

**Issue by RejectKid** [JonPSmith/EfCore.GenericServices#58]
Per your Book example with the IncludeThen.  When I do a `genericService.ReadSingleAsync<Book>(id);` am i to expect the list of Reviews to come with it as well? or is this only for the saving bit?

**Comment by chrisbbe** [comment]
No, `Task<T> ReadSingleAsync<T>(params object[] keys)` will not load related entities per se.

You could use `IQueryable<T> ReadManyNoTracked<T>()` like this:

```
var bookWithReviews = services.ReadManyNoTracked<Book>()
        .Include(x => x.Reviews)
        .Where(x => x.Id == 1)
        .SingleOrDefault();
```

to load the book with reviews in one DB round trip. I myself miss support for `[IncludeThen(nameof(Book.Reviews))]` on the DTO for `ReadSingleAsync<T>`. This should be possible to implement, right @JonPSmith ?

**Comment by JonPSmith** [comment]
Hi @RejectKid,

@chrisbbe is correct than `ReadSingleAsync<T>` doesn't use the `IncludeThen` attribute. That's because the DTO readd allow you  allows you to map relationships. In my unit tests I map all the Author's name when reading a book. Below are links to this unit test and its DTO and config.

- Unit Test: [TestReadSingleCollectionAuthors](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/UnitTests/GenericServicesPublic/TestReadViaDto.cs#L134L159)
- DTO: [BookWithAuthors](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/Dtos/BookWithAuthors.cs)
- Config: [BookWithAuthorsConfig](https://github.com/JonPSmith/EfCore.GenericServices/blob/master/Tests/Configs/BookWithAuthorsConfig.cs)

> This should be possible to implement, right @JonPSmith ?

To answer @chrisbbe question I _could_ make `IncludeThen` work for reads of an entity, but I don't think its a good idea because loading large collections can make the load take more time. Better to use a DTO and extract the specific data/calculations by creating a `PerDtoConfig<TDto, TEntity>` class.

I hope that helps.
