### ISSUE TITLE
Unable to map read only collections

### ISSUE THREAD

**Issue by tesnep** [JonPSmith/EfCore.GenericServices#7]
I don't know if you have already tried this but if you wanted to map reviews in BookListDto it will silently fail.
DataLayer.EfClasses.Book
```c#
public IEnumerable<Review> Reviews => _reviews?.ToList();
```
If you create a property Reviews in BookListDto 
```
public IEnumerable<Review> Reviews {get; private set;}
```
It will always be null even if you override in AlterReadMapping.
``` C#
public override Action<IMappingExpression<Book, BookDto>> AlterReadMapping
        {
            get
            {
                return cfg => cfg
                    .ForMember(x => x.Reviews, y => y.MapFrom(p => p.Reviews));
                    // or below
                   // .ForMember(x => x.Reviews, opt => opt.UseDestinationValue());
            }
        }
```
However, I do notice that you have a way to get Reviews count in BookListDto

```c#
.ForMember(x => x.ReviewsCount, x => x.MapFrom(book => book.Reviews.Count()))
```

**Comment by JonPSmith** [comment]
Hi @tesnep,

Thanks for sharing that - a useful suggestion. 

I tend to use nested DTOs so that I can pick what I want to extract in the query. The Wiki documentation has a section on [Nested DTOs](https://github.com/JonPSmith/EfCore.GenericServices/wiki/GenericServices-and-DTOs#nested-dtos), with a link to an example in the unit tests.
