### ISSUE TITLE
[Question] Loading a Aggregate Root entity

### ISSUE THREAD

**Issue by baoduy** [JonPSmith/EfCore.GenericServices#8]
Hi, JonPSmith
Reading your EF Core book and planning to start a new project with EF core and follow DDD pattern. This library is useful and I plan to use it in the project. However, I have a question regarding to loading the Aggregate Root from Db we need to load all linking entity as well so when executing the IQuerydable we need to include all linking properties. Could you please recommend where should I place the including logic?

Thanks and Regards
Duy

**Comment by JonPSmith** [comment]
Hi Duy,

There are a few ways to do that, but I will explain how I go about this (with references to the book):

In Chapter 2 I cover *Query Objects* in section 2.6. That is s useful part to look at. My first question is, "do you really near to load ALL the linking entities (the aggregates)". I tend to use a Select query (section 2.4.3) to load exactly what I need. The example in section 2.6 is a good one, as I pick parts of the data from the aggregates rather than loading them all.

The up side of this approach is that a) the code for each query is easy to find/refactor because its in sepecifc Query objects, and b) it performs well because it only loads what it needs. The down side is you can end up writing a lot of small query objects, but I fixed that by building my library '[EfCore.GenericServices](https://github.com/JonPSmith/EfCore.GenericServices)' which uses AutoMapper (see section 10.3) to build Select queries from the DTOs you provide. 

For completeness some people recommend a repository pattern for accessing the database, and I describe that in section 10.4. The problem is I find creating a repository in the data layer doesn't perform as well as Query Objects which can sit in the Service Layer - see section 10.4.3. for a critique of the DDD implementation I show in section 10.4 of the book.

I hope that gives you some more places to read and make up your mind on how to build your application. 

PS. Since the book I use DDD-styled entity classes in every project I work on - see [this article on my blog site](https://www.thereformedprogrammer.net/creating-domain-driven-design-entity-classes-with-entity-framework-core/) which describes the specific ways I do that.

**Comment by baoduy** [comment]
Hi @JonPSmith 

Thanks for your reply, It realy useful and I will go with this approach, Since EF Core 2.1 supports Lazy Load. So instead of providing the DbConext to each buz actions We can create a private constructor with a LazyLoader parameter and load the make the linking properties load data on demand as below article.

https://docs.microsoft.com/en-us/ef/core/querying/related-data

Thanks for your response again and EF Core is a very useful book which I have read and helped me to learn and implement the DDD for the new applications

Cheers
Duy

**Comment by JonPSmith** [comment]
Hi @baoduy,

I'm glad that was helpful. I'm not a fan of lazy loading for performance reasons, especially in queries, but I think it's a good solution for loading relationships you want to update them. 

NOTE: You don't have to provide a LazyLoader parameter if you use the Microsoft.EntityFrameworkCore.Proxies NuGet library and virtual relationship properties.
