### ISSUE TITLE
Setup with WPF correct?

### ISSUE THREAD

**Issue by Falthazar** [JonPSmith/EfCore.GenericServices#9]
I wanted to try and use this library for a practice app I am building, using WPF. I plan to eventually change the WPF to a web app, but thought it'd be easier to learn EF core/DI when I can build a quick interface and not have to learn web stuff as well. 

Been reading your book and the Dependency Injection in .Net as well, so I am pretty knew to both concepts.

To start, I decided to build a WPF UI (using Caliburn Micro) on top of the example GenericServices project, just to get a hang of everything. I did have to change the target frameworks for both the Service and Data layers to .Net Standard 2.0, but everything still built correctly.

Only question so far is why I needed to add Autofac as a dependency in the WPF project for GenericServices to work? I thought that would be okay just being referenced in GenericServices?
For reference, I'm using SimpleInjector for my DI container.

Here is the configuration code I wrote, is this setup correctly?
```C#
        private Container _container;
        protected override void Configure()
        {
            this._container = new Container();
            this._container.Options.DefaultScopedLifestyle = new ThreadScopedLifestyle();
            
            //This is for Caliburn Micro
            this._container.RegisterSingleton<IWindowManager, WindowManager>();
            this._container.RegisterSingleton<IEventAggregator, EventAggregator>();

            this._container.Register<ShellWindowViewModel>();
            this._container.Register<BooksListViewModel>();

            SetupContextAndCrudServices();
            this._container.Verify();
        }

        private void SetupContextAndCrudServices()
        {
            var context = SetupEfContext();
            var crudServices = SetUpCrudServices(context);
            // Does the context even need to be registered? Or can I just register it in CrudServices?
            this._container.Register<EfCoreContext>(SetupEfContext, Lifestyle.Scoped);
            this._container.Register<ICrudServices>(() => SetUpCrudServices(context), Lifestyle.Scoped);
        }

        private EfCoreContext SetupEfContext()
        {
            var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = ":memory:" };
            var connectionString = connectionStringBuilder.ToString();
            var connection = new SqliteConnection(connectionString);
            connection.Open();
            var options = new DbContextOptionsBuilder<EfCoreContext>();
            options.UseSqlite(connection);

            var context = new EfCoreContext(options.Options);
            context.DevelopmentEnsureCreated();
            context.SeedDatabase(Directory.GetCurrentDirectory());

            return context;
        }

        private ICrudServices SetUpCrudServices(EfCoreContext context)
        {
            // Just wanted to start off with the one, but to add more I would just do
            //     utData.AddSingleDto<>() for each dto to add?
            var utData = context.SetupSingleDtoAndEntities<BookListDto>();
            return new CrudServices<EfCoreContext>(context, utData.ConfigAndMapper);
        }
       
       // More WPF specific stuff 
```

**Comment by JonPSmith** [comment]
Hi @Falthazar,

You certainly don't need to dependence injection (DI) to make GenericService to work, so what you are doing will work. In ASP.NET Core DI is the preferred way to link things together, hence I use DI (I also find DI VERY useful, I would always use DI in medium/large projects).

Your `SetUpCrudServices` is fine. I do provide a method to register the service which also scans for DTOs. That is useful when you have lots of DTOs, and also makes sure you don't miss any DTOs.

On AutoFac I only showed that because it automates the registering of multiple services - again a time saver for larger applications.

**Comment by JonPSmith** [comment]
Hi @Falthazar,

I wasn't suggesting your implementation is incorrect - it's fine (and what I would use in a Azure Function). I was only explaining why I talked so much about DI in the book, because chapter 5 is about using EF Core in an ASP.NET Core application.

Carry on what you are doing - its all good.
